version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aviyon
      POSTGRES_USER: aviyon_user
      POSTGRES_PASSWORD: aviyon_pass
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
