app_root:
    path: /
    controller: App\Controller\AuthController::root

landing:
    path: /landing
    controller: App\Controller\AuthController::landing

login:
    path: /login
    controller: App\Controller\AuthController::login

signup:
    path: /signup
    controller: App\Controller\AuthController::signup

marketplace:
    path: /marketplace
    controller: App\Controller\AuthController::marketplace

user_profile:
    path: /user/{username}
    controller: App\Controller\AuthController::userProfile

about:
    path: /about
    controller: App\Controller\AuthController::about

ide:
    path: /ide
    controller: App\Controller\AuthController::ide

search:
    path: /search
    controller: App\Controller\AuthController::search
    methods: [GET]

add_comment:
    path: /comment
    controller: App\Controller\AuthController::addComment
    methods: [POST]

like_post:
    path: /like
    controller: App\Controller\AuthController::likePost
    methods: [POST]

explore:
    path: /explore
    controller: App\Controller\AuthController::explore
