user:
    resource: '../config/routes/user.yaml'

careers:
    resource: '../config/routes/careers.yaml'

auth:
    resource: '../config/routes/auth.yaml'

docs:
    resource: '../config/routes/docs.yaml'

marketplace:
    resource: '../config/routes/marketplace.yaml'

about:
    resource: '../config/routes/about.yaml'

admin:
    resource: '../config/routes/admin.yaml'

dashboard:
    resource: '../config/routes/dashboard.yaml'

messages:
    resource: '../config/routes/messages.yaml'

settings:
    resource: '../config/routes/settings.yaml'

investing:
    resource: '../config/routes/investing.yaml'

notifications:
    resource: '../config/routes/notifications.yaml'

pages:
    resource: '../config/routes/pages.yaml'

wallet:
    resource: '../config/routes/wallet.yaml'

news:
    resource: '../config/routes/news.yaml'

post:
    resource: '../config/routes/post.yaml'

bulletinboard:
    resource: '../config/routes/bulletinboard.yaml'

ticker:
    resource: '../config/routes/ticker.yaml'

global_feed:
    resource: '../config/routes/global_feed.yaml'

explore:
    resource: '../config/routes/explore.yaml'
