app_root:
    path: /
    controller: App\Controller\AuthController::root

login:
    path: /login
    controller: App\Controller\AuthController::login

signup:
    path: /signup
    controller: App\Controller\AuthController::signup

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

features:
    path: /features
    controller: App\Controller\PageController::features

about:
    path: /about
    controller: App\Controller\PageController::about

checkout:
    path: /checkout
    controller: App\Controller\PageController::checkout

domain:
    path: /domain
    controller: App\Controller\PageController::domain

search:
    path: /search
    controller: App\Controller\PageController::search

user:
    path: /user
    controller: App\Controller\PageController::user

settings:
    path: /settings
    controller: App\Controller\PageController::settings

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

dashboard_ide:
    path: /dashboard/ide
    controller: App\Controller\DashboardController::ide

dashboard_deployments:
    path: /dashboard/deployments
    controller: App\Controller\DashboardController::deployments

dashboard_hosting:
    path: /dashboard/hosting
    controller: App\Controller\DashboardController::hosting

dashboard_agents:
    path: /dashboard/agents
    controller: App\Controller\DashboardController::agents

dashboard_marketplace:
    path: /dashboard/marketplace
    controller: App\Controller\DashboardController::marketplace

dashboard_virtual_world:
    path: /dashboard/virtual-world
    controller: App\Controller\DashboardController::virtualWorld

dashboard_messages:
    path: /dashboard/messages
    controller: App\Controller\DashboardController::messages

dashboard_nimbus_ai:
    path: /dashboard/nimbus-ai
    controller: App\Controller\DashboardController::nimbusAi

admin:
    path: /admin
    controller: App\Controller\AdminController::index
