# config/services.yaml
services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # Automatically register all controllers in src/Controller as services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Add other service definitions if needed
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Manually register the StringExtension for Twig (optional, can be removed if not needed)
    twig.extension.string:
        class: Twig\Extra\String\StringExtension
        tags:
            - { name: twig.extension }

    # Register the custom AppExtension
    App\Twig\AppExtension:
        tags: ['twig.extension']
